[package]
name = "cookbook"
version = "0.1.0"
authors = ["farteen <xujavacn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.6"
serde = "1.0.24"
serde_derive = "1.0.24"