[package]
name = "cookbook"
version = "0.1.0"
authors = ["farteen <xujavacn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
csv = "1.1.3"
